### ISSUE TITLE
SWAG missing `lsio` network example from docker-compose examples

### ISSUE THREAD

**Issue by ChrisRomp** [linuxserver/docker-documentation#39]
The CLI examples mostly use `--net=lsio` to demonstrate an existing bridge network, but none of the docker-compose files have it.  Was that intentional?  I believe this is the correct syntax for that if you wish to include it.  If not, no worries.

```
---
version: "2.1"
services:
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - URL=linuxserver-test.com
      - SUBDOMAINS=www,ombi
      - VALIDATION=http
    volumes:
      - /home/aptalca/appdata/swag:/config
    networks:
      lsio:
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped

networks:
  lsio:
    external: true
```
